export interface Module {
  name: string;
  port: string;
  url: string;
  display: Display;
  source: string;
  tags: {
    name: string;
    subject_name: Subject;
  }[];
}

export enum Subject {
  Math = 'Mathematics',
  Science = 'Science',
  Arts = 'Arts & Humanities',
  Literature = 'Literature',
  Languages = 'Languages',
  Technology = 'Technology',
  EverydayLife = 'Everyday Life',
  SocialSciences = 'Social Sciences',
}

export enum Math {
  Foundational = 'Foundational Mathematics',
  Algebra = 'Algebra',
  Geometry = 'Geometry',
  Stats = 'Statistics & Probability',
  Calculus = 'Calculus',
  Engineering = 'Engineering',
  Tests = 'Tests & Textbooks',
}

export enum Science {
  General = 'General Science',
  Biology = 'Biology',
  Chemistry = 'Chemistry',
  Physics = 'Physics',
  Astronomy = 'Astronomy',
  EarthSciences = 'Earth Sciences',
}

export enum Arts {
  History = 'History',
  Geography = 'Geography',
  Religion = 'Religious Studies',
  Art = 'Art & Design',
  Music = 'Music',
  Culture = 'Culture & People',
}

export enum Literature {
  Fiction = 'Fiction & Non-Fiction',
  Tests = 'Tests & Textbooks',
  Reading = 'Reading & Spelling',
}

export enum Technology {
  Social = 'Social Media & Internet',
  Computers = 'Computers',
  Programming = 'Programming & Computing',
}

export enum EverydayLife {
  EverydayLife = 'Everyday Life',
  Careers = 'Careers',
  Farming = 'Farming & Agriculture',
  Resource = 'Resource Management',
  HumanHealth = 'Human Health & Healthcare',
  AnimalHealth = 'Animal Health',
  Environment = 'Environment',
  Infrastructure = 'Infrastruture',
  Practical = 'Practical Skills',
}

export enum SocialSciences {
  Economics = 'Economics',
  Development = 'Development & Business',
  Citizenship = 'Citizenship',
}

export enum Languages {
  SouthAfrica = 'South African Languages',
  SouthAndEast = 'Southern & East African Languages',
  World = 'World Langauges',
}

export const TagMap = {
  [Subject.Math]: Math,
  [Subject.Science]: Science,
  [Subject.Arts]: Arts,
  [Subject.Literature]: Literature,
  [Subject.Technology]: Technology,
  [Subject.EverydayLife]: EverydayLife,
  [Subject.SocialSciences]: SocialSciences,
  [Subject.Languages]: Languages,
}

export enum Display {
  Primary = 'primary',
  Secondary = 'secondary',
  Text = 'text'
}


// This is an old interface, only used for pulling the seed data for the backend
export interface DataObject {
  name: string;
  port: string;
  url: string;
  type: string;
  by: string;
  tags: {
    [Subject.Math]?: Math,
    [Subject.Science]?: Science,
    [Subject.Arts]?: Arts,
    [Subject.Literature]?: Literature,
    [Subject.Technology]?: Technology,
    [Subject.EverydayLife]?: EverydayLife,
    [Subject.SocialSciences]?: SocialSciences,
    [Subject.Languages]?: Languages,
  }
}

// export const data: DataObject[] = [
//   {
//     name: 'Math',
//     port: '8008',
//     url: '/learn/khan/math',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Early Math',
//     port: '8008',
//     url: '/learn/khan/math/early-math/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Arithmetic',
//     port: '8008',
//     url: '/learn/khan/math/arithmetic/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Pre-algebra',
//     port: '8008',
//     url: '/learn/khan/math/pre-algebra/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Algebra basics',
//     port: '8008',
//     url: '/learn/khan/math/algebra-basics/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Algebra I',
//     port: '8008',
//     url: '/learn/khan/math/algebra/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Basic Geometry',
//     port: '8008',
//     url: '/learn/khan/math/basic-geo/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Geometry },
//   },
//   {
//     name: 'Geometry',
//     port: '8008',
//     url: '/learn/khan/math/geometry/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Geometry },
//   },
//   {
//     name: 'Algebra II',
//     port: '8008',
//     url: '/learn/khan/math/algebra2/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Trigonometry',
//     port: '8008',
//     url: '/learn/khan/math/trigonometry/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Geometry },
//   },
//   {
//     name: 'Probability and statistics',
//     port: '8008',
//     url: '/learn/khan/math/probability/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Stats },
//   },
//   {
//     name: 'Precalculus',
//     port: '8008',
//     url: '/learn/khan/math/precalculus/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Calculus },
//   },
//   {
//     name: 'Differential calculus',
//     port: '8008',
//     url: '/learn/khan/math/differential-calculus/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Calculus },
//   },
//   {
//     name: 'Integral calculus',
//     port: '8008',
//     url: '/learn/khan/math/integral-calculus/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Calculus },
//   },
//   {
//     name: 'Multivariable calculus',
//     port: '8008',
//     url: '/learn/khan/math/multivariable-calculus/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Calculus },
//   },
//   {
//     name: 'Differential equations',
//     port: '8008',
//     url: '/learn/khan/math/differential-equations/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Math for fun and glory',
//     port: '8008',
//     url: '/learn/khan/math/math-for-fun-and-glory/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Science',
//     port: '8008',
//     url: '/learn/khan/science',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.General },
//   },
//   {
//     name: 'Biology',
//     port: '8008',
//     url: '/learn/khan/science/biology/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.Biology },
//   },
//   {
//     name: 'Physics',
//     port: '8008',
//     url: '/learn/khan/science/physics/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.Physics },
//   },
//   {
//     name: 'Chemistry',
//     port: '8008',
//     url: '/learn/khan/science/chemistry/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.Chemistry },
//   },
//   {
//     name: 'Organic Chemistry',
//     port: '8008',
//     url: '/learn/khan/science/organic-chemistry/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.Chemistry },
//   },
//   {
//     name: 'Cosmology and astronomy',
//     port: '8008',
//     url: '/learn/khan/science/cosmology-and-astronomy/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Science]: Science.Astronomy },
//   },
//   {
//     name: 'Health and medicine',
//     port: '8008',
//     url: '/learn/khan/science/health-and-medicine/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Electrial engineering',
//     port: '8008',
//     url: '/learn/khan/science/electrical-engineering/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Math]: Math.Engineering },
//   },
//   {
//     name: 'Economics and finance',
//     port: '8008',
//     url: '/learn/khan/economics-finance-domain/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.SocialSciences]: SocialSciences.Economics },
//   },
//   {
//     name: 'Microeconomics',
//     port: '8008',
//     url: '/learn/khan/economics-finance-domain/microeconomics/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.SocialSciences]: SocialSciences.Economics },
//   },
//   {
//     name: 'Macroeconomics',
//     port: '8008',
//     url: '/learn/khan/economics-finance-domain/macroeconomics/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.SocialSciences]: SocialSciences.Economics },
//   },
//   {
//     name: 'Finance and capital markets',
//     port: '8008',
//     url: '/learn/khan/economics-finance-domain/core-finance/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.SocialSciences]: SocialSciences.Economics },
//   },
//   {
//     name: 'Entrepreneurship',
//     port: '8008',
//     url: '/learn/khan/economics-finance-domain/entrepreneurship2/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.EverydayLife]: EverydayLife.Careers },
//   },
//   {
//     name: 'Computing',
//     port: '8008',
//     url: '/learn/khan/computing/',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Technology]: Technology.Programming },
//   },
//   {
//     name: 'Computer programming',
//     port: '8008',
//     url: '/learn/khan/computing/computer-programming',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Technology]: Technology.Programming },
//   },
//   {
//     name: 'Computer science',
//     port: '8008',
//     url: '/learn/khan/computing/computer-science',
//     type: 'module',
//     by: 'KA Lite Essentials',
//     tags: { [Tag.Technology]: Technology.Programming },
//   },
//   {
//     name: 'English',
//     port: '8010',
//     url: '/modules/en-afristory/english.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Afrikaans',
//     port: '8010',
//     url: '/modules/en-afristory/afrikaans.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'isiNdebele',
//     port: '8010',
//     url: '/modules/en-afristory/isindebele.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'isiXhosa',
//     port: '8010',
//     url: '/modules/en-afristory/isixhosa.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'isiZulu',
//     port: '8010',
//     url: '/modules/en-afristory/isizulu.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Sepedi',
//     port: '8010',
//     url: '/modules/en-afristory/sepedi.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Sesotho (Lesotho)',
//     port: '8010',
//     url: '/modules/en-afristory/sesotho-lesotho.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Sesotho (South Africa)',
//     port: '8010',
//     url: '/modules/en-afristory/sesotho-safrica.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Setswana',
//     port: '8010',
//     url: '/modules/en-afristory/setswana.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Siswati',
//     port: '8010',
//     url: '/modules/en-afristory/siswati.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Tshivenda',
//     port: '8010',
//     url: '/modules/en-afristory/tshivenda.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Xitsonga',
//     port: '8010',
//     url: '/modules/en-afristory/xitsonga.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.SouthAfrica,
//     },
//   },
//   {
//     name: 'Kiswahili',
//     port: '8010',
//     url: '/modules/en-afristory/swahili.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.Tanzania,
//     },
//   },
//   {
//     name: 'Maa',
//     port: '8010',
//     url: '/modules/en-afristory/maa.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.Tanzania,
//     },
//   },
//   {
//     name: 'English 2',
//     port: '8010',
//     url: '/modules/en-afristory/english2.html',
//     type: 'module+',
//     by: 'African Storybooks',
//     tags: {
//       [Tag.Literature]: Literature.Fiction,
//       [Tag.Languages]: Languages.Tanzania,
//     },
//   },
//   {
//     name: 'Algebra',
//     port: '8010',
//     url: '/modules/en-ck12/Algebra.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Algebra },
//   },
//   {
//     name: 'Geometry',
//     port: '8010',
//     url: '/modules/en-ck12/Geometry.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Geometry },
//   },
//   {
//     name: 'Trigonometry',
//     port: '8010',
//     url: '/modules/en-ck12/Trigonometry.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Geometry },
//   },
//   {
//     name: 'Calculus',
//     port: '8010',
//     url: '/modules/en-ck12/Calculus.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Calculus },
//   },
//   {
//     name: 'Grade 6 (11-12 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/math6.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Grade 7 (12-13 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/math7.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Grade 8 (13-14 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/math8.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Biology',
//     port: '8010',
//     url: '/modules/en-ck12/Biology.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.Biology },
//   },
//   {
//     name: 'Physics',
//     port: '8010',
//     url: '/modules/en-ck12/Physics.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.Physics },
//   },
//   {
//     name: 'Chemistry',
//     port: '8010',
//     url: '/modules/en-ck12/Chemistry.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.Chemistry },
//   },
//   {
//     name: 'Astronomy',
//     port: '8010',
//     url: '/modules/en-ck12/Astronomy.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.Astronomy },
//   },
//   {
//     name: 'Discoveries and Projects',
//     port: '8010',
//     url: '/modules/en-ck12/Discoveries.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.General },
//   },
//   {
//     name: 'Earth Sciences 1 (11-14 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/Earth_Science_MS.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.EarthSciences },
//   },
//   {
//     name: 'Earth Sciences 2 (14-18 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/Earth_Science_2.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.EarthSciences },
//   },
//   {
//     name: 'Physical Sciences (11-14 years old) - U.S. Curriculum',
//     port: '8010',
//     url: '/modules/en-ck12/Physical_Science.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Science]: Science.EarthSciences },
//   },
//   {
//     name: 'Engineering',
//     port: '8010',
//     url: '/modules/en-ck12/Engineering.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Math]: Math.Engineering },
//   },
//   {
//     name: 'U.S. History',
//     port: '8010',
//     url: '/modules/en-ck12/US_History.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Arts]: Arts.History },
//   },
//   {
//     name: 'Spelling',
//     port: '8010',
//     url: '/modules/en-ck12/Spelling.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: { [Tag.Literature]: Literature.Reading },
//   },
//   {
//     name: 'U.S. SAT1 (College Entrance Exam)',
//     port: '8010',
//     url: '/modules/en-ck12/SAT1.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: {
//       [Tag.Math]: Math.Tests,
//       [Tag.Literature]: Literature.Tests,
//     },
//   },
//   {
//     name: 'U.S. SAT2 (College Entrance Exam)',
//     port: '8010',
//     url: '/modules/en-ck12/SAT2.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: {
//       [Tag.Math]: Math.Tests,
//       [Tag.Literature]: Literature.Tests,
//     },
//   },
//   {
//     name: 'U.S. SAT3 (College Entrance Exam)',
//     port: '8010',
//     url: '/modules/en-ck12/SAT3.pdf',
//     type: 'pdf',
//     by: 'CK-12 Textbooks',
//     tags: {
//       [Tag.Math]: Math.Tests,
//       [Tag.Literature]: Literature.Tests,
//     },
//   },
//   {
//     name: 'Top 100 Favorites',
//     port: '8010',
//     url: '/modules/en-ebooks/top100favorites.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Top 100 Non-Fiction',
//     port: '8010',
//     url: '/modules/en-ebooks/top100nonfiction.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Adventure',
//     port: '8010',
//     url: '/modules/en-ebooks/adventure.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Biographies',
//     port: '8010',
//     url: '/modules/en-ebooks/biographies.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: "Children's Stories",
//     port: '8010',
//     url: '/modules/en-ebooks/childrensstories.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Comedy & Humor',
//     port: '8010',
//     url: '/modules/en-ebooks/comedyhumor.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Drama',
//     port: '8010',
//     url: '/modules/en-ebooks/drama.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Fantasy',
//     port: '8010',
//     url: '/modules/en-ebooks/fantasy.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Folklore',
//     port: '8010',
//     url: '/modules/en-ebooks/folklore.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Historical Fiction',
//     port: '8010',
//     url: '/modules/en-ebooks/historicalfiction.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Historical Non-Fiction',
//     port: '8010',
//     url: '/modules/en-ebooks/historicalnonfiction.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Horror',
//     port: '8010',
//     url: '/modules/en-ebooks/horror.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Mystery',
//     port: '8010',
//     url: '/modules/en-ebooks/mystery.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Philosophy & Religion',
//     port: '8010',
//     url: '/modules/en-ebooks/philosophyreligion.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Poetry',
//     port: '8010',
//     url: '/modules/en-ebooks/poetry.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Romance',
//     port: '8010',
//     url: '/modules/en-ebooks/romance.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Science Fiction',
//     port: '8010',
//     url: '/modules/en-ebooks/sciencefiction.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Short Stories',
//     port: '8010',
//     url: '/modules/en-ebooks/shortstories.html',
//     type: 'module',
//     by: 'Great Books of the World',
//     tags: { [Tag.Literature]: Literature.Fiction },
//   },
//   {
//     name: 'Career Planning',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/careerplanning.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.EverydayLife]: EverydayLife.Careers },
//   },
//   {
//     name: 'Computers',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/computers.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Devices',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/devices.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Digital Lifestyle',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/digitalskills.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Social },
//   },
//   {
//     name: 'Email Basics',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/emailbasics.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Everyday Life',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/everydaylife.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.EverydayLife]: EverydayLife.EverydayLife },
//   },
//   {
//     name: 'Internet Basics',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/internet.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Social },
//   },
//   {
//     name: 'Job Development',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/jobsearch.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.EverydayLife]: EverydayLife.Careers },
//   },
//   {
//     name: 'Mac OS Basics',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/macos.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Math Basics',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/math.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Money',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/money.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.EverydayLife]: EverydayLife.EverydayLife },
//   },
//   {
//     name: 'Online Safety',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/onlinesafety.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Social },
//   },
//   {
//     name: 'Photos and Graphics',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/photosandgraphics.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Reading',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/reading.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Literature]: Literature.Reading },
//   },
//   {
//     name: 'Social Media',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/socialmedia.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Social },
//   },
//   {
//     name: 'Using the Cloud',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/usingthecloud.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.Technology]: Technology.Social },
//   },
//   {
//     name: 'Workplace Skills',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/workplaceskills.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//     tags: { [Tag.EverydayLife]: EverydayLife.Careers },
//   },
//   {
//     name: 'Hesperian Health Guides',
//     port: '8010',
//     url: '/modules/en-hesperian_health/',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Where There Is No Doctor. A village health care handbook.',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_wtnd_2011_full/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Where There Is No Dentist',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_dent_2012_full/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Where Women Have No Doctor',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_wwhnd_2012_full/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Disabled Village Children',
//     port: '8010',
//     url: '/modules/en-hesperian_health/DVC_2009/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Women with Disabilities - A Health Handbook',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_WWD_2008_full_book/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'A Book for Midwives: Care for pregnancy and birth',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_midw_2011_Full_Book/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Helping Children Who Are Deaf',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_hcwd_2004_Full_Book/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Helping Children Who Are Blind',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_hcwb_2000_whole_book/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Cholera Prevention Fact Sheet',
//     port: '8010',
//     url: '/modules/en-hesperian_health/Cholera_EN/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Sanitation and Cleanliness for a Healthy Environment',
//     port: '8010',
//     url: '/modules/en-hesperian_health/EHB_Sanitation_EN_watermark/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Water for Life - Community water security',
//     port: '8010',
//     url: '/modules/en-hesperian_health/ehb_water_EN_watermark/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'A Community Guide to Environmental Health',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_cgeh_2012_full/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Helping Health Workers Learn',
//     port: '8010',
//     url: '/modules/en-hesperian_health/en_hhwl_2012_full/page1.html',
//     type: 'pdf',
//     by: 'Hesperian Health Guides',
//     tags: {},
//   },
//   {
//     name: 'Plant',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$text$-1$plantHealth.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Crops, fruits, vegetables and grains',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$crops.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Pests and diseases',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$pests.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Medicinal plants',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$medicinalPlants.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Fruit and vegetable processing',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$farmPlanningAndMarketing.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Natural pest control',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$recipesForOrganicPesticides.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Cultural control practices',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$soilFertilityManagement.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Human',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$text$-1$humanHealth.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Healthy food',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$healthyFood.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Nutrition related diseases',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$nutrition.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Insect transmitted diseases',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$humanDiseases.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Zoonotic diseases',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$zoonoticDiseases.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Hygiene and sanitation',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$hygiene.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Animals',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$text$-1$animalHealth.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Animal husbandry and welfare',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$animalKeeping.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Livestock species and commercial insects',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$livestockSpecies.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Livestock health and diseases',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$animalDiseases.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Fodder production',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$fodder.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Products',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$products.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.AnimalHealth },
//   },
//   {
//     name: 'Environment',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$text$-1$environmentalHealth.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Environment },
//   },
//   {
//     name: 'Agro-ecological zones',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$agrozones.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Water management',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$soilConservation.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Soil management',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$soilManagement.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Sustainable and organic agriculture',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$sustainableLandManagement.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Conservation agriculture',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$biodiversity.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Trees',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$agroforestry.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Processing and value addition',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$ovvImg$-1$incomeGeneration.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'The Organic Farmer - Magazine',
//     port: '8010',
//     url: '/modules/en-infonet/export/default$text$-1$orgFarmerGroup.html',
//     type: 'module',
//     by: 'Infonet - Biovision',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'A-Ag',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_A-Ag.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Ah-Ap',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Ah-Ap.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Aq-Az',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Aq-Az.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'B-Bk',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_B-Bk.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Bl-Bz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Bl-Bz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'C-Cg',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_C-Cg.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Ch-Co',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Ch-Co.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Cp-Cz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Cp-Cz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'D-Di',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_D-Di.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Dj-Dz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Dj-Dz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'E-Ep',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_E-Ep.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Eq-Ez',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Eq-Ez.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'F',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_F.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'G',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_G.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'H-Hf',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_H-Hf.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Hg-Hz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Hg-Hz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'I-In',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_I-In.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Io-Iz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Io-Iz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'J',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_J.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'K',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_K.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'L-Ln',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_L-Ln.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Lo-Lz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Lo-Lz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'M-Mf',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_M-Mf.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Mg-Mz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Mg-Mz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'N',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_N.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'O',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_O.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'P-Pl',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_P-Pl.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Pm-Pz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Pm-Pz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Q',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Q.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'R',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_R.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'S-Sh',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_S-Sh.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Si-Sp',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Si-Sp.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Sq-Sz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Sq-Sz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'T-Tn',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_T-Tn.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'To-Tz',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_To-Tz.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'U',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_U.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'V',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_V.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'W',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_W.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'X',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_X.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Y',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Y.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Z',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_Z.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: '0-9',
//     port: '8010',
//     url: '/modules/en-medline_plus/ency/encyclopedia_0-9.htm',
//     type: 'module',
//     by: 'Medline Plus',
//     tags: { [Tag.EverydayLife]: EverydayLife.HumanHealth },
//   },
//   {
//     name: 'Music Theory',
//     port: '8010',
//     url: '/modules/en-musictheory/index.html',
//     type: 'module',
//     by: 'Music Theory',
//     tags: { [Tag.Arts]: Arts.Music },
//   },
//   {
//     name: 'Agriculture',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Construction',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Infrastructure },
//   },
//   {
//     name: 'Crop processing',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Disaster response, mitigation and rebuilding',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Infrastructure },
//   },
//   {
//     name: 'Energy',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Infrastructure },
//   },
//   {
//     name: 'Environment and adaptation to climate change',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Environment },
//   },
//   {
//     name: 'Fisheries',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Food processing',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Information, communication, learning',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: {
//       [Tag.Technology]: Technology.Social,
//       [Tag.EverydayLife]: EverydayLife.Practical,
//     },
//   },
//   {
//     name: 'Livestock',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Farming },
//   },
//   {
//     name: 'Manufacturing, handicraft, process industries',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Practical },
//   },
//   {
//     name: 'Natural resources management',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Social and economic development',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.SocialSciences]: SocialSciences.Development },
//   },
//   {
//     name: 'Transport and infrastructure',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Infrastructure },
//   },
//   {
//     name: 'Waste management',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Water and sanitation',
//     port: '8010',
//     url: '/modules/en-practical_action/index.html',
//     type: 'module',
//     by: 'Practical Action',
//     tags: { [Tag.EverydayLife]: EverydayLife.Resource },
//   },
//   {
//     name: 'Art',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Art.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Art },
//   },
//   {
//     name: 'Business Studies',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Business_Studies.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.SocialSciences]: SocialSciences.Development },
//   },
//   {
//     name: 'Citizenship',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Citizenship.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.SocialSciences]: SocialSciences.Citizenship },
//   },
//   {
//     name: 'Countries',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Countries.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Geography },
//   },
//   {
//     name: 'Design and Technology',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Design_and_Technology.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Art },
//   },
//   {
//     name: 'Everyday life',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Everyday_life.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.EverydayLife]: EverydayLife.EverydayLife },
//   },
//   {
//     name: 'Geography',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Geography.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Geography },
//   },
//   {
//     name: 'History',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.History.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.History },
//   },
//   {
//     name: 'IT',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.IT.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Technology]: Technology.Computers },
//   },
//   {
//     name: 'Language and Literature',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Language_and_literature.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Languages]: Languages.World },
//   },
//   {
//     name: 'Mathematics',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Mathematics.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Math]: Math.Foundational },
//   },
//   {
//     name: 'Music',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Music.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Music },
//   },
//   {
//     name: 'People',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.People.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Culture },
//   },
//   {
//     name: 'Portals',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Portals.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Culture },
//   },
//   {
//     name: 'Religion',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Religion.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Arts]: Arts.Religion },
//   },
//   {
//     name: 'Science',
//     port: '81',
//     url: '/wikipedia_en_for_schools_opt_2013/A/wp/index/subject.Science.htm',
//     type: 'module',
//     by: 'Wikipedia for Schools',
//     tags: { [Tag.Science]: Science.General },
//   },
//   {
//     name: 'Wikivoyage',
//     port: '81',
//     url: '/wikivoyage_en_all_2016-04/',
//     type: 'module',
//     by: 'Wikivoyage',
//     tags: { [Tag.Arts]: Arts.Geography },
//   },
//   {
//     name: 'Wiktionary',
//     port: '81',
//     url: '/wiktionary_en_all_2015-11/',
//     type: 'module',
//     by: 'Wiktionary',
//     tags: { [Tag.Languages]: Languages.World },
//   },
//   {
//     name: 'Interactive World Map',
//     port: '8010',
//     url: '/modules/en-worldmap/map.html',
//     type: 'module',
//     by: 'Interactive World Map',
//     tags: { [Tag.Arts]: Arts.Geography },
//   },
// ].sort((a, b) => a.name.localeCompare(b.name));

// export const resources = [
//   {
//     name: 'Office 2000',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/office2000.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Office 2003',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/office2003.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Office 2007',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/office2007.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Office 2010',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/office2010.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Office 2013',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/office2013.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Office XP',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/officeXP.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'OpenOffice',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/openoffice.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Windows',
//     port: '8010',
//     url: '/modules/en-GCF2015/content/windows.html',
//     type: 'module',
//     by: 'GCF Learnfree',
//   },
//   {
//     name: 'Mozilla Firefox',
//     port: '8010',
//     url: '/modules/en-windows_apps/FirefoxPortable_65.0.2_English.paf.exe',
//     type: 'module',
//     by: 'Windows Applications',
//   },
//   {
//     name: 'OpenOffice Suite',
//     port: '8010',
//     url: '/modules/en-windows_apps/OpenOfficePortable_4.1.5_MultilingualStandard.paf.exe',
//     type: 'module',
//     by: 'Windows Applications',
//   },
//   {
//     name: 'VLC Video Player',
//     port: '8010',
//     url: '/modules/en-windows_apps/VLCPortable_3.0.4.paf.exe',
//     type: 'module',
//     by: 'Windows Applications',
//   },
//   {
//     name: 'Putty SSH',
//     port: '8010',
//     url: '/modules/en-windows_apps/PuTTYPortable_0.70_English.paf.exe',
//     type: 'module',
//     by: 'Windows Applications',
//   },
// ].sort((a, b) => a.name.localeCompare(b.name));

export const subjects = Object.values(Subject);
export const sources = ['African Storybooks', 'CK-12 Textbooks', 'GCF Learnfree', 'Great Books of the World', 'Hesperian Health Guides', 'Infonet - Biovision', 'Interactive World Map', 'KA Lite Essentials', 'Medline Plus', 'Music Theory', 'Practical Action', 'Wikipedia for Schools', 'Wikivoyage', 'Wiktionary'];
